import Link from "next/link";
import { LandingFork } from "@/components/landing-fork";
import { DiagnosisCard } from "@/components/report-cards";
import { Brand, ConnectLink, Icon, MockLabel, SectionHeading } from "@/components/ui";
import { demoDiagnosis } from "@/lib/data/fixture";

export default function Home() {
  return <div className="landing">
    <section className="landing-hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" />FOR CREATORS READY FOR THEIR NEXT CHAPTER</p><h1>See why your<br />channel <em>stalled.</em></h1><p className="hero-description">You built an audience. Now build a direction.<br />Turn your YouTube history into a clear diagnosis and three considered paths forward.</p><div className="button-row"><ConnectLink /><Link className="text-link" href="/dashboard?demo=1">Preview a demo channel <span aria-hidden="true">↗</span></Link></div><p className="hero-fine">Your full initial plan is free. Your creative judgment stays yours.</p><div className="hero-bottom"><span className="hero-line" /><span>LESS GUESSWORK.<br /><strong>MORE PERSPECTIVE.</strong></span></div></div></section>
    <div className="principle-strip"><span><b>01</b> Understand the pattern</span><span><b>02</b> Explore the trade-offs</span><span><b>03</b> Learn from what happens</span></div>
    <section className="landing-section landing-brief" aria-label="Illustrative strategy brief"><LandingFork /></section>
    <section id="approach" className="landing-section"><SectionHeading number="01" eyebrow="THE SPACE BETWEEN DATA AND DIRECTION" title="You have the numbers.
You need the next move." /><div className="approach-grid"><p className="editorial-copy">A plateau rarely asks for more of the same. It asks you to look at what built your audience — and what has changed.</p><div className="approach-steps"><article><span>01 / UNDERSTAND</span><h3>Find the reason beneath the trend.</h3><p>A focused diagnosis, grounded in your own history. Every claim comes with its evidence.</p></article><article><span>02 / CONSIDER</span><h3>See the trade-offs before the effort.</h3><p>Explore three 12-week scenarios. Compare the commitment, possible growth, and risk of each.</p></article><article><span>03 / RECALIBRATE</span><h3>Let real results change the plan.</h3><p>Compare a checkpoint with what happened, then make the next week more informed.</p></article></div></div></section>
    <section className="landing-section sample-section"><SectionHeading number="02" eyebrow="A DIFFERENT KIND OF CHANNEL REPORT" title="A useful insight has a reason."><MockLabel label="Illustrative diagnosis" /></SectionHeading><DiagnosisCard diagnosis={demoDiagnosis.diagnosis} /><p className="fine-print">Sample channel and metrics shown for illustration. A connected report uses your own channel history.</p></section>
    <section className="landing-section economics-section"><div><p className="eyebrow">STRATEGIC THINKING, WITHIN REACH</p><h2>A little more clarity.<br /><em>A lot more agency.</em></h2><p>CreatorLENS handles performance analysis, content planning, and scenario exploration. You bring the taste, relationships, and final decision.</p><div className="ownership-list"><span><Icon name="check" size={16} />Your creative voice</span><span><Icon name="check" size={16} />Your community</span><span><Icon name="check" size={16} />Your final call</span></div></div><div className="economics-card"><div><p>Human growth strategist</p><strong>SGD 800–2,500<span>/ month</span></strong><small>Indicative range · varies by scope</small></div><div className="economics-pro"><p>CreatorLENS Pro <span className="section-pill">TARGET PRICE</span></p><strong>~SGD 30<span>/ month</span></strong><small>Pricing to be validated with creators</small></div><p className="fine-print">Start with a free diagnosis, a complete initial plan, and your first recalibration. Pro continues the feedback loop.</p></div></section>
    <section id="scope" className="scope-strip"><div><p className="eyebrow">CLEAR ABOUT THE SCOPE</p><h3>Useful means honest.</h3></div><p>YouTube is the focus. Instagram and TikTok are visibly mocked previews. Scenarios carry assumptions. A backtest number appears only after it has been measured.</p></section>
    <section className="landing-section faq-section"><div><p className="eyebrow">A FEW THINGS WORTH ASKING</p><h2>Clarity starts<br />with good questions.</h2></div><div className="faq-list">
      <details><summary>Who is CreatorLENS for?<span aria-hidden="true">+</span></summary><p>Creators with roughly 50,000–200,000 subscribers and one to three years of posting history, who are considering a new direction after growth has slowed.</p></details>
      <details><summary>Is this predicting my subscriber count?<span aria-hidden="true">+</span></summary><p>No. The chart explores scenarios based on the relationship between your past cadence, format mix, and growth. It assumes those relationships continue. Uncertainty increases further into the 12 weeks.</p></details>
      <details><summary>How is it different from an analytics dashboard?<span aria-hidden="true">+</span></summary><p>The workflow connects your history to a diagnosis, lets you explore alternative strategies, then compares the plan with actual results at a checkpoint. You can use it alongside the analytics tools you already rely on.</p></details>
      <details><summary>What do I get for free?<span aria-hidden="true">+</span></summary><p>Your diagnosis, Content DNA, content ideas and hooks, all three initial 12-week plans, and the week-2 recalibration. Later recalibrations are the proposed Pro tier. This build demonstrates the unlock without taking payment.</p></details>
      <details><summary>How do I know whether the model is useful?<span aria-hidden="true">+</span></summary><p>The intended check walks forward through your own past weeks and compares short-range estimates with what happened. We show an error number only when that backtest has actually run. The demo does not claim measured accuracy.</p></details>
    </div></section>
    <section className="closing-cta"><p className="eyebrow">YOUR HISTORY IS A STARTING POINT.</p><h2>Make your next move<br /><em>a considered one.</em></h2><div className="button-row"><ConnectLink /><Link className="text-link" href="/dashboard?demo=1">Take a look first ↗</Link></div></section>
    <footer className="landing-footer"><Brand /><p>Evidence first. Your call, always.</p><span>Built for your next chapter.</span></footer>
  </div>;
}
