import Link from "next/link";
import { Brand, ConnectLink, Icon } from "@/components/ui";

export default function Home() {
  return <div className="landing">
    <section className="landing-hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" />FOR CREATORS GROWING WITH SHORT-FORM CONTENT</p><h1><em>Grow with us.</em></h1><p className="hero-description">You built an audience. Now build a direction.<br />Turn your channel history into a clear diagnosis and three considered short-form content strategies.</p><div className="button-row"><ConnectLink /><Link className="text-link" href="/dashboard?demo=1">Preview a demo channel <span aria-hidden="true">↗</span></Link></div><p className="hero-fine">Your full initial plan is free. Your creative judgment stays yours.</p><div className="hero-bottom"><span className="hero-line" /><span>LESS GUESSWORK.<br /><strong>MORE PERSPECTIVE.</strong></span></div></div></section>
    <section id="approach" className="landing-section economics-section"><div><p className="eyebrow">STRATEGIC THINKING, WITHIN REACH</p><h2>A little more clarity.<br /><em>A lot more agency.</em></h2><p>CreatorLENS handles performance analysis, content planning, and scenario exploration. You bring the taste, relationships, and final decision.</p><div className="ownership-list"><span><Icon name="check" size={16} />Your creative voice</span><span><Icon name="check" size={16} />Your community</span><span><Icon name="check" size={16} />Your final call</span></div></div><div className="economics-card"><div><p>Human growth strategist</p><strong>SGD 800–2,500<span>/ month</span></strong><small>Indicative range · varies by scope</small></div><div className="economics-pro"><p>CreatorLENS Pro <span className="section-pill">TARGET PRICE</span></p><strong>~SGD 30<span>/ month</span></strong><small>Pricing to be validated with creators</small></div><p className="fine-print">Start with a free diagnosis, a complete initial plan, and your first recalibration. Pro continues the feedback loop. YouTube is the focus today — Instagram and TikTok are visibly mocked previews.</p></div></section>
    <section className="landing-section faq-section"><div><p className="eyebrow">A FEW THINGS WORTH ASKING</p><h2>Clarity starts<br />with good questions.</h2></div><div className="faq-list">
      <details><summary>Who is CreatorLENS for?<span aria-hidden="true">+</span></summary><p>Creators with roughly 50,000–200,000 subscribers who post short-form content regularly, and whose growth has slowed.</p></details>
      <details><summary>Is this predicting my subscriber count?<span aria-hidden="true">+</span></summary><p>No. The chart explores scenarios based on the relationship between your past posting cadence, the topics they cover, and your growth. It assumes those relationships continue. Uncertainty increases further into the 12 weeks.</p></details>
      <details><summary>What do I get for free?<span aria-hidden="true">+</span></summary><p>Your diagnosis, content ideas and hooks, all three initial 12-week strategies, and the week-2 recalibration. Later recalibrations are the proposed Pro tier. This build demonstrates the unlock without taking payment.</p></details>
    </div></section>
    <section className="closing-cta"><p className="eyebrow">YOUR HISTORY IS A STARTING POINT.</p><h2>Make your next move<br /><em>a considered one.</em></h2><div className="button-row"><ConnectLink /><Link className="text-link" href="/dashboard?demo=1">Take a look first ↗</Link></div></section>
    <footer className="landing-footer"><Brand /><p>Evidence first. Your call, always.</p><span>Built for your next chapter.</span></footer>
  </div>;
}
